# Without this reloading config will not unbind old keys
unbind-key -a -T root

set -g pane-border-lines double

set  -g base-index      1
setw -g pane-base-index 1

#setw -g mode-keys   vi
set  -g focus-events on

set  -g mouse             on
set  -s escape-time       0
set  -g history-limit     2000

set  -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB,*256col*:RGB,alacritty:RGB,kitty:RGB"

set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

bind -n M-r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"
bind -n M-s choose-tree -s

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -n M-C-Left resize-pane -L 5
bind -n M-C-Right resize-pane -R 5
bind -n M-C-Up resize-pane -U 3
bind -n M-C-Down resize-pane -D 3

bind -n M-h split-window -v
bind -n M-v split-window -h

bind -n M-Enter new-window
bind -n M-c kill-pane
bind -n M-q kill-window
bind -n M-d detach
bind -n M-Q confirm-before -p "Kill entire session? (y/n)" kill-session

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy || xclip -in -selection clipboard"
bind -n M-/ copy-mode \; command-prompt -p "(search down)" "send -X search-forward '%%%'"
bind -n M-? copy-mode \; command-prompt -p "(search up)"   "send -X search-backward '%%%'"

# mouse scroll
bind -T root WheelUpPane   if-shell -F "#{mouse_any_flag}" "send-keys -M" "copy-mode -e"
bind -T root WheelDownPane if-shell -F "#{mouse_any_flag}" "send-keys -M" "send-keys -M"
bind -T copy-mode-vi WheelUpPane   send-keys -X scroll-up
bind -T copy-mode-vi WheelDownPane send-keys -X scroll-down
bind -T copy-mode WheelUpPane      send-keys -X scroll-up
bind -T copy-mode WheelDownPane    send-keys -X scroll-down


set -g @catppuccin_flavor 'frappe'

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
set -g status-left ""
set -g status-right '#[fg=#{@thm_crust},bg=#{@thm_teal}] session: #S '

# Ensure that everything on the right side of the status line
# is included.
set -g status-right-length 100

set -g @plugin 'tmux-plugins/tpm'

#set -g @plugin 'egel/tmux-gruvbox'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'


set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

run '~/.config/tmux/plugins/tpm/tpm'
