preload = /home/npc/Изображения/wallp/forest.jpg
wallpaper = DP-2, /home/npc/Изображения/wallp/forest.jpg
#preload = /home/npc/Изображения/приколы/1293921.png

#wallpaper = DP-3, /home/npc/Изображения/приколы/1293921.png
# preload = /home/npc/Изображения/приколы/1303038-3840x2160-desktop-4k-spice-and-wolf-anime-wallpaper-photo.jpg

# wallpaper = DP-3, /home/npc/Изображения/приколы/1303038-3840x2160-desktop-4k-spice-and-wolf-anime-wallpaper-photo.jpg
